### ISSUE TITLE
Add a list of monitored and ranged regions to ESTBeaconManager

### ISSUE THREAD

**Issue by kdaker** [Estimote/iOS-SDK#143]
Why doesn't ESTBeaconManager expose the currently monitored regions like CLLocationManager? 

If I call startMonitoring on the same beacon twice, does ESTBeaconManager ignore duplicates?

**Comment by jcb1973** [comment]
Just checking - I think this is resolved by the addition of monitoredRegions and rangedRegions properties for ESTBeaconManager and ESTSecureBeaconManager in release 3.2.2. Is this what you were expecting? If not, let us know. Thanks again for the feedback!
