### ISSUE TITLE
SDK deosnt work in static library

### ISSUE THREAD

**Issue by onskulis** [Estimote/iOS-SDK#148]
Hello,

I'm trying to use Estimote SDK in static library. Everything seems to be fine, but none of the methods are firing up (didEnterRegion, didExitRegion, didStart, didFail, etc) when I'm trying to start to monitore a region. I have included every framework that Estimote needs, every header file(headers are found for sure) and set under Capabilities: Background Modes ON, checked Location Updates, Acts as a Bluetooth LE accessory and Uses Bluetooth LE accessories. All of this I've done as well in my static library as in test app. Im sure my start() method is being fired up, checked it already with NSLog(@"started"); But the following code:

#import "ads.h"
#import "ESTBeaconManager.h"
#import "ESTBeaconRegion.h"

@interface ads () <ESTBeaconManagerDelegate>

@property (nonatomic, strong) ESTBeaconManager* BeaconManager;
@property (nonatomic, strong) ESTBeacon* Beacon;
@property (nonatomic, strong) ESTBeaconRegion* BeaconRegion;

@end

@implementation ads

-(void)startAds {
    NSLog(@"Started");
    self.BeaconManager = [[ESTBeaconManager alloc] init];
    self.BeaconManager.delegate = self;
   
    self.BeaconRegion = [[ESTBeaconRegion alloc] initWithProximityUUID:ESTIMOTE_PROXIMITY_UUID identifier:@"LOL"];
    self.BeaconRegion.notifyEntryStateOnDisplay = YES;
    self.BeaconRegion.notifyOnEntry = YES;
    [self.BeaconManager startMonitoringForRegion:self.BeaconRegion];
}

- (void)beaconManager:(ESTBeaconManager *)manager didStartMonitoringForRegion:(ESTBeaconRegion *)region {
    NSLog(@"STARTED MONITORE");
}

- (void)beaconManager:(ESTBeaconManager *)manager monitoringDidFailForRegion:(ESTBeaconRegion *)region withError:(NSError *)error {
    NSLog(@"FAILED TO START");
}

@end

Is absolutely dead. It does absolutely nothing. May I know is it impossible to use SDK in static library or is it iOS issue? Or where is the problem? Im testing on Iphone 5S, iOS version 7.1, Bluetooth ON, Locations ON. Tried to restart the phone many times, turn on flight mode, off, restart and etc etc.

Best Regards.

**Comment by heypiotr** [comment]
Seems like everything's sorted out here, so I'm closing this one. If you feel otherwise, please feel free to re-open the issue.
