### ISSUE TITLE
Beacon connect does not invoke delegate callbacks

### ISSUE THREAD

**Issue by haric** [Estimote/iOS-SDK#164]
We are seeing connection issues with  2.2.1..the only way the connection seems to succeed is through the ESTIMOTE App..In our case, connect does not seem to perform callbacks (success or failure) as it used to.  Have tried with Secure ID turned on and OFF.

**Comment by heypiotr** [comment]
Closing old issues, if anyone can reproduce with 3.0, feel free to reopen and let us know!
