### ISSUE TITLE
didRangeBeacons not returning region

### ISSUE THREAD

**Issue by victorcstn** [Estimote/iOS-SDK#165]
I am ranging on two different regions. When the delegate didRangeBeacons is called I receive nil values for Region and therefore I can discard which region is responsible for the returning values. Is that normal? Is that happening to anyone else?

**Comment by heypiotr** [comment]
The recent release, which added an `inMotion` property to our ESTBeaconRegion, introduced a slight change to how we pass regions around internally, also fixing a couple of bugs. Can you check if this issue still happens with the newest version of the SDK?

**Comment by heypiotr** [comment]
@victorcstn, can you re-try with the newest version of the SDK? Can you also make sure that [returnAllRangedBeaconsAtOnce](http://estimote.github.io/iOS-SDK/Classes/ESTBeaconManager.html#//api/name/returnAllRangedBeaconsAtOnce) is not set to `true` on your ESTBeaconManager?

**Comment by heypiotr** [comment]
There was a bug with the ESTBeaconRegion that sometimes resulted in this behavior. In SDK 3.0 we removed ESTBeaconRegion altogether, you now use plain CLBeaconRegions instead, so this problem will no longer occur.

**Comment by victorcstn** [comment]
Thanks Piotr,

I am using it already.

On 8 April 2015 at 11:47, Piotr Krawiec <notifications@github.com> wrote:

> There was a bug with the ESTBeaconRegion that sometimes resulted in this
> behavior. In SDK 3.0 we removed ESTBeaconRegion altogether, you now use
> plain CLBeaconRegions instead, so this problem will no longer occur.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Estimote/iOS-SDK/issues/165#issuecomment-90864699>.
>



-- 
Best regards

*Victor Castano*
E-mail: archipestre@gmail.com
