### ISSUE TITLE
Get MFI PPID for publishing

### ISSUE THREAD

**Issue by silvialillocci** [Estimote/iOS-SDK#169]
I build an app with iBeacon Estimote and it is rejected from iTunes Connect.

This is the message: 
"Your app has not Been authorized by the accessory manufacturer to work with the MFi accessory. Please contact the accessory manufacturer to request your app be added to the MFi Product Plan form.
Once the accessory manufacturer Confirms That your app Has Been added to the MFi Product Plan form, please reply to this message. When we receive your reply with this confirmation, we can proceed with the review; we do not require a new binary even though your application in iTunes Connect have been is Rejected.
If you have not yet provided the accessory's MFi Plan Product ID (PPID), please enter this information in the Notes section for your app in iTunes Connect. If you do not know the PPID, please request this information from the accessory manufacturer. "

Where can I find this number?

**Comment by heypiotr** [comment]
Are you by any chance using the External Accessory background mode?

Also, since this is not really SDK related, let's move this conversation to contact@estimote.com—just shoot us an email and our support team will be happy to help. Thanks!

**Comment by Ne3maRayan** [comment]
i have same problem , please any help well be greatly appreciated

**Comment by Ne3maRayan** [comment]
please if you can help me , contact me at bblsft@gmail.com

**Comment by heypiotr** [comment]
You need to disable the background modes for your application—they're not needed to use Estimote SDK and Beacons, even in the background.

**Comment by Ne3maRayan** [comment]
my app connect to zebra printer by bluetooth , i contact zebra and they give me PPID and add app to white list , but apple still reject app !!!

**Comment by Ne3maRayan** [comment]
i didn't use  Beacons , i use Zebra SDK ,, BUT I  get same rejection reason

**Comment by heypiotr** [comment]
You need to inquire with the reviewers then.

**Comment by Ne3maRayan** [comment]
ok thanks !
