### ISSUE TITLE
Incorrect Library search paths in Example Framework Paths

### ISSUE THREAD

**Issue by eskerber** [Estimote/iOS-SDK#171]
2 Issues:

1.) Estimate library path is `../EstimoteSDK`, which is no longer valid now that the examples are nested in an estimote directory. It should be `../../EstimoteSDK`

2.) Hardcoded user path

![screen shot 2014-12-31 at 3 52 43 pm](https://cloud.githubusercontent.com/assets/75236/5590775/1dc1d592-9105-11e4-8338-835748db6e40.png)

**Comment by heypiotr** [comment]
Fixed, let's have some :cake: to celebrate! (:
