### ISSUE TITLE
Build Issue with 2.3.0 SDK

### ISSUE THREAD

**Issue by ianxxiao** [Estimote/iOS-SDK#172]
I followed the manual install instruction but received the following build error. Any ideas? Thanks a lot.

undef: _OBJC_CLASS_$_ESTBeaconInternalUtilities
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_ESTBeaconInternalUtilities", referenced from:
      objc-class-ref in libEstimoteSDK.a(ESTRequestRegisterNearable.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by TheoJL** [comment]
I'm also seeing this in 2.3.0, but my message says arm64.

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_ESTBeaconInternalUtilities", referenced from:
      objc-class-ref in libEstimoteSDK.a(ESTRequestRegisterNearable.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by brightsider** [comment]
And I'm seeing this in 2.3.0. Please, fix it!

**Comment by breiko83** [comment]
Same problem here.
Temporary switched to 2.2.1 with:

    pod 'EstimoteSDK', '< 2.3'

**Comment by domas** [comment]
Yes same problem here. As @breiko83 suggested downgrading to 2.2.1 fixed it for now

**Comment by heypiotr** [comment]
We just pushed 2.3.1 live, which fixes the issue. Thanks for your feedback!
