### ISSUE TITLE
ESTNearableManagerDelegate nearableManager:didExitTypeRegion: is never called

### ISSUE THREAD

**Issue by divineprog** [Estimote/iOS-SDK#174]
*Problem:*

When monitoring by nerable type, ESTNearableManagerDelegate method nearableManager:didExitTypeRegion: is never called.

nearableManager:didEnterTypeRegion: is called as expected. 

*How to reproduce:*

I used the Cordova Estimote plugin example app BeaconFinder to test, code is here:

https://github.com/divineprog/phonegap-estimotebeacons

The type to monitor for is set in file app.js on line 383:

https://github.com/divineprog/phonegap-estimotebeacons/blob/master/examples/beacon-finder/www/js/app.js#L383

Also tested the nearables/MonitoringExample in the Estimote iOS SDK which I didn't get to work.

I will be happy to help with debugging if I can.

**Comment by divineprog** [comment]
Done some testing with iOS SDK 2.4.0.

Neither of nearableManager:didExitTypeRegion:  and nearableManager:didEnterTypeRegion: is called.

With previous SDK nearableManager:didExitTypeRegion: was called.

Also tested the MonitoringExample app in the iOS SDK. It does not pick up my Dog sticker, but picked up an 'unknown' prototype sticker. At one point the Dog sticker and the prototype sticker were show alternating in the list (still one list item). Selecting the sticker in the list produced this crash:

    2015-02-10 18:41:47.484 MonitoringExample[370:60b] -[CLLocationManager requestAlwaysAuthorization]: unrecognized selector sent to instance 0x16e61160
    2015-02-10 18:41:47.489 MonitoringExample[370:60b] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[CLLocationManager requestAlwaysAuthorization]: unrecognized selector sent to instance 0x16e61160'

Used an iPhone 4S with iOS 7.0.6 to test. Perhaps this is not a supported iOS version? Will test with a newer device.

**Comment by martinklimek** [comment]
@divineprog try to test with latest commit: 7058088e9ec31b5bb2e9f13c6ef8fb494b18ce4a it should work now.

**Comment by divineprog** [comment]
Thanks will have a look!

**Comment by jcb1973** [comment]
Tested nearables monitoring as part of pre-release checks this morning - working in SDK 3.2.7. Please let us know of any further problems!
