### ISSUE TITLE
Triggers don't update state when a nearable goes out of range

### ISSUE THREAD

**Issue by mikaelkindborg** [Estimote/iOS-SDK#176]
**Problem description:**

Triggers update state when a nearable goes into range, but not when it goes out of range.

**How to reproduce:**

Tested this with a "Dog" sticker.

Did the test by modifying the "TriggersExample" example app.

Rules and triggers:

```
ESTProximityRule *dogCloseRule = [ESTProximityRule inRangeOfNearableType: ESTNearableTypeDog];
ESTTrigger *dogCloseTrigger = [[ESTTrigger alloc] initWithRules:@[dogCloseRule] identifier:@"DogClose"];

ESTProximityRule *dogAwayRule = [ESTProximityRule outsideRangeOfNearableType: ESTNearableTypeDog];
ESTTrigger *dogAwayTrigger = [[ESTTrigger alloc] initWithRules:@[dogAwayRule] identifier:@"DogAway"];

[self.triggerManager startMonitoringForTrigger:dogCloseTrigger];
[self.triggerManager startMonitoringForTrigger:dogAwayTrigger];
```

Trigger state change method:

```
- (void)triggerManager:(ESTTriggerManager *)manager triggerChangedState:(ESTTrigger *)trigger
{
    if ([trigger.identifier isEqualToString:@"DogClose"] && trigger.state == YES)
    {
        NSLog(@"Dog is close");
    }
    else
    {
        NSLog(@"Dog is not close");
    }

    if ([trigger.identifier isEqualToString:@"DogAway"] && trigger.state == YES)
    {
        NSLog(@"Dog is away");
    }
    else
    {
        NSLog(@"Dog is not away");
    }
}
```

The log displays the following when the sticker is close to the mobile phone:

```
2015-02-09 20:55:20.196 TriggersExample[670:60b] Dog is close
2015-02-09 20:55:20.200 TriggersExample[670:60b] Dog is not away
```

When the sticker moves out of range, no state change events are triggered.

Also tested with only the "DogClose" trigger, with the same result.

Perhaps this is by design? Expected the trigger to report the state change.

**Comment by fabioknoedt** [comment]
In my experience, you need different `ESTTriggerManager` to listen to different triggers state changes.
You can't use the same `ESTTriggerManager` for different triggers like you wrote:
```
[self.triggerManager startMonitoringForTrigger:dogCloseTrigger];
[self.triggerManager startMonitoringForTrigger:dogAwayTrigger];
```
You need to use something like:
```
[self.triggerManagerClose startMonitoringForTrigger:dogCloseTrigger];
[self.triggerManagerAway startMonitoringForTrigger:dogAwayTrigger];
```

**Comment by greggS** [comment]
Hey,
There is no need to create separate trigger managers or separate triggers and rules. One rule created using "inRangeOfNearableType" should be enough. Please try initializing it with identifier instead of type and test if it works for you. Also make sure you didn't accidentally created the triggerManager property as assign.

**Comment by mikaelkindborg** [comment]
@fabioknoedt @greggS Thanks for this info!

**Comment by MatthewAnthonyBordas** [comment]
Please close this out if the issue was solved resolved :)

**Comment by heypiotr** [comment]
I actually don't think this is fixed yet. I'll leave it open until our engineers find a moment to verify.
