### ISSUE TITLE
After RGB codes for the colours

### ISSUE THREAD

**Issue by jimbobbennett** [Estimote/iOS-SDK#178]
I'm working on my sample app for my Xamarin bindings, and wanted to display details about the beacons using the actual colours.  Do you have the RGB values for the different colour constants anywhere?

Thanks

**Comment by heypiotr** [comment]
We do not have the actual constants in the SDK, that's probably a neat idea. For now, the RGB values below:

mint: R:159 G:205 B:174
icy: R:110 G:206 B:245
blueberry: R:46 G:49 B:146

**Comment by jimbobbennett** [comment]
Thanks.  Would be nice to have them defined in the SDK for all the beacons/nearables.
