### ISSUE TITLE
Bridging header with swift

### ISSUE THREAD

**Issue by datomnurdin** [Estimote/iOS-SDK#183]
I want to use swift for this ios sdk. what kind of header that I need to import inside my project based on this tutorial?

http://estimote.com/api/tutorials/distance.html

**Comment by heypiotr** [comment]
Hey there,

You need the following imports in your bridging header:

```
#import "ESTBeaconManager.h"
#import "ESTConfig.h"
```

This should get you covered.

Since GitHub issues are more for bug reports, I encourage you to post questions like this one on our brand new [Community Forums](http://forums.estimote.com/), e.g. in the "Support" section.
