### ISSUE TITLE
No documents for ESTUtilityManager and ESTUtilityManagerDelegate

### ISSUE THREAD

**Issue by setomits** [Estimote/iOS-SDK#184]
I've just cloned master branch, and noticed that there are no HTML files for ESTUtilityManager and ESTUtilityManagerDelegate even they are online.
http://estimote.github.io/iOS-SDK/Classes/ESTUtilityManager.html
http://estimote.github.io/iOS-SDK/Protocols/ESTUtilityManagerDelegate.html

**Comment by heypiotr** [comment]
Thanks for your report, we're aiming to fix this in the upcoming bug-fix release! :ok_hand:

**Comment by martinklimek** [comment]
It was fixed with 44c6e81ad9e1ba28ee4b1984fb7f0abd89dfeb77
