### ISSUE TITLE
startEstimoteBeaconsDiscoveryForRegion: not starting in background

### ISSUE THREAD

**Issue by evgzor** [Estimote/iOS-SDK#185]
I am using estiomote iOS SDK ver.2.0 for long time and do not want switch to latest one. I would like to use start and stop discovery beacon in background. But startEstimoteBeaconsDiscoveryForRegion: does not work in background. Could u please help me?

**Comment by heypiotr** [comment]
At this time, `startEstimoteBeaconsDiscoveryForRegion` is coded such that it only works in the foreground—we do not consider this a bug, as we never promised it'll work in the background. We are however considering making it work this way in one of the upcoming releases, so if you could share why exactly you need this particular method (and not regular ranging or monitoring), that'd help inform our decision (:

Thanks!
