### ISSUE TITLE
ESTNearableManager delegate methods not called in background

### ISSUE THREAD

**Issue by Rich86man** [Estimote/iOS-SDK#186]
When monitoring a nearable identifier with code such as 

`    [self.nearableManager startMonitoringForIdentifier:self.nearableIdentifier];``

in the foreground I get entered and exited delegate notifications through these methods

`- (void)nearableManager:(ESTNearableManager *)manager didEnterIdentifierRegion:(NSString *)identifier
`
`- (void)nearableManager:(ESTNearableManager *)manager didExitIdentifierRegion:(NSString *)identifier
`

but when my app goes into the background I no longer receive these notifications.

I've tested the same code with a beacon, and I receive the similar ESTBeaconManager monitoring notifications.

**Comment by heypiotr** [comment]
Have you enabled the bluetooth-central background mode for your app? Since stickers use a non-iBeacon advertising packet, they require this background mode to keep operating in the background—unlike our regular beacons, which benefit from the iBeacon's built-in, background-monitoring capabilities.

**Comment by Rich86man** [comment]
Yes that seems to have done the trick. Thanks!
