### ISSUE TITLE
No sound push notification.

### ISSUE THREAD

**Issue by datomnurdin** [Estimote/iOS-SDK#187]
When I got exit region push notification, I didn't receive any sound. Same goes to enter region push notification.

**Comment by heypiotr** [comment]
There's no sound for notifications by default, you need to explicitly code it in. Take a look the the [soundName](https://developer.apple.com/library/ios/documentation/iPhone/Reference/UILocalNotification_Class/#//apple_ref/occ/instp/UILocalNotification/soundName) property of the UILocalNotification.
