### ISSUE TITLE
ESTSecureBeaconManager - nothing detected during ranging with region based solely on proximityUUID

### ISSUE THREAD

**Issue by jpstern** [Estimote/iOS-SDK#188]
I am calling startRanging on an instance of ESTSecureBeaconManager with the following region

[[CLBeaconRegion alloc] initWithProximityUUID:ESTIMOTE_PROXIMITY_UUID identifier:@"default"];

**The didRangeBeacons delegate function always returns 0 beacons.**

When I change the region to include a specific minor value like this:

[[CLBeaconRegion alloc] initWithProximityUUID:ESTIMOTE_PROXIMITY_UUID **major:11111** identifier:@"default"];

**The didRangeBeacons function will now return the beacon**

**Is this expected behavior when using Secure UUID?**

**Comment by heypiotr** [comment]
No, that's definitely not expected. Let us look into it!

**Comment by martinklimek** [comment]
Hi @jpstern:) We found a bug and corrected that with 3.1.0 release.
