### ISSUE TITLE
iOS-SDK is incompatible with Swift 1.2

### ISSUE THREAD

**Issue by gleslie2008** [Estimote/iOS-SDK#189]
Objective-C methods from `BeaconManagerDelegate` can no longer be called in `Swift 1.2` as shown in the tutorial.

`Objective-C method 'beaconManager:didEnterRegion:' provided by method 'beaconManager(_:didEnterRegion:)' conflicts with optional requirement method 'beaconManager(_:didEnterRegion:)' in protocol 'ESTBeaconManagerDelegate'`

`Objective-C method 'beaconManager:didExitRegion:' provided by method 'beaconManager(_:didExitRegion:)' conflicts with optional requirement method 'beaconManager(_:didExitRegion:)' in protocol 'ESTBeaconManagerDelegate'`

`Objective-C method 'beaconManager:didRangeBeacons:inRegion:' provided by method 'beaconManager(_:didRangeBeacons:inRegion:)' conflicts with optional requirement method 'beaconManager(_:didRangeBeacons:inRegion:)' in protocol 'ESTBeaconManagerDelegate'`

**Comment by heypiotr** [comment]
Which tutorial do you have in mind?

`BeaconManagerDelegate` can still be used just fine with Swift 1.2. It's only, the latest version of Swift performs a strict check to match the method signatures: `(id)` needs to become `AnyObject!` and `(NSArray *)` needs to become `[AnyObject!]`. When in doubt, you can always remove the method's original signature and insert a fresh one via Xcode's autocompletion.

**Comment by gleslie2008** [comment]
Hi @heypiotr,

Using the same steps as this tutorial: https://community.estimote.com/hc/en-us/articles/202478933-How-to-build-an-Estimote-compatible-app-with-Swift-

Creating a class that extends `ESTBeaconManagerDelegate` and adding the method:
`func beaconManager(manager: ESTBeaconManager!, didEnterRegion region: CLBeaconRegion!) {
        // code
    }`
for example, causes the error:
`Objective-C method 'beaconManager:didEnterRegion:' provided by method 'beaconManager(_:didEnterRegion:)' conflicts with optional requirement method 'beaconManager(_:didEnterRegion:)' in protocol 'ESTBeaconManagerDelegate'`

**Comment by heypiotr** [comment]
Ha, thanks for sharing. This article is long overdue for an update, we'll get to that.

In this particular case, the correct method signature is:

```
func beaconManager(manager: AnyObject!, didEnterRegion region: CLBeaconRegion!)
```

i.e. `ESTBeaconManager` becomes `AnyObject!`.

Longer story: in SDK 3.0 we introduced separate beacon managers for regular beacons and beacons secured with our [Secure UUID](https://community.estimote.com/hc/en-us/articles/204233603-How-security-feature-works) technology: `ESTBeaconManager` and `ESTSecureBeaconManager`. They both use a common delegate, the `ESTBeaconManagerDelegate`, so we can no longer guarantee that the `manager` object passed to the delegate will be of `ESTBeaconManager` type (b/c it can just as well be an `ESTSecureBeaconManager`). So we made it an `id` type, which in Swift translates to `AnyObject!`.

**Comment by gleslie2008** [comment]
Got it.  Thank you for the explanation and quick reply!

**Comment by giluna** [comment]
**Hi heypiotr,**

I'm using Estimote SDK 3.7.0 swift and deployment target 7.0

Using:
```
func beaconManager(manager: AnyObject!, didRangeBeacons beacons: [AnyObject]!, inRegion region: CLBeaconRegion!) {
// ... 
}
```
Still gives me the next error:

Objective-C method 'beaconManager:didRangeBeacons:inRegion:' provided by method 'beaconManager(_:didRangeBeacons:inRegion:)' conflicts with optional requirement method 'beaconManager(_:didRangeBeacons:inRegion:)' in protocol 'ESTBeaconManagerDelegate'

 any suggestions?

**Comment by heypiotr** [comment]
We added nullability and generics annotations in 3.7.0, so the signature of the `didRangeBeacons` method changed to:

```
func beaconManager(manager: AnyObject, didRangeBeacons beacons: [CLBeacon], inRegion region: CLBeaconRegion) {
// ... 
}
```

It looks like Xcode 7 issues a warning, and can automatically fix the signature disparity if the only thing that changed is the nullability annotations; but issues an error and can't automatically fix the signature if generics annotation was added (here: `[CLBeacon]` instead of `[AnyObject]`). So you need to fix it manually.
