### ISSUE TITLE
adjusting ESTBeaconRegion size

### ISSUE THREAD

**Issue by jsanders67** [Estimote/iOS-SDK#190]
Is there a way I can set my beacon region to be smaller for a given beacon (certain major or minor or both)? 
Alternatively, is there a way to only trigger the didRangeBeacons, or didEnterRegion/diExitRegion for a region radius that is smaller than that of the one given to a standard beacon?

I would like to be able to register a ping of beacon while the app is in the background, when the iOS device is very close to a certain beacon.

Thanks

**Comment by martinklimek** [comment]
Hi @jsanders67, 

To make beacon region smaller you can play with beacons power (using AppStore app or SDK Examples). Smaller the power smaller the range. There is no mechanism provided by Apple that allows you to ping in defined distance. You can use only monitoring in background and enter/exit events are fired always when you came into range of beacon - so the power setting is the only option here.
