### ISSUE TITLE
Crash in [ESTBeaconDevice cleanCharasteristics]

### ISSUE THREAD

**Issue by souhl** [Estimote/iOS-SDK#191]
Hi,
after disconnect we got a crash in above function in line 40.
Any idea what my cause this? We have crash dump if needed.

Thanks
Sascha

**Comment by martinklimek** [comment]
@souhl is this duplicate of #195 ?

**Comment by souhl** [comment]
@martinklimek may be.. the error was different. But we didnt got it again. I close it.
