### ISSUE TITLE
Include Estimote SDK into framework

### ISSUE THREAD

**Issue by rafaelrsilva** [Estimote/iOS-SDK#196]
Hello!
I need to implement a cocoa touch framework that includes EstimoteSDK. This framework would contain all beacons implementations (didEnterRegion, didExitRegion, didRangeBeacon, ...).
All apps that need to use beacons would implement this cocoa framework and done, the app is already monitoring and ranging beacons.

Is it possible to implement? Does it need a special setting? 
tks!

**Comment by heypiotr** [comment]
Hey, don't see any reason why this wouldn't be doable (:

Have you tried this solution?
http://stackoverflow.com/questions/27484997/how-to-create-an-umbrella-framework-in-ios-sdk

I'll close this issue to keep the list clean (our SDK engineers use it to plan their sprints), and I encourage you to use [our forums](https://forums.estimote.com) to discuss this any further. Cheers!
