### ISSUE TITLE
ESTBeaconConnection writeName:completion: and utf-8 failures

### ISSUE THREAD

**Issue by jverdi** [Estimote/iOS-SDK#198]
Hi, I'm attempting to write a utf-8 NSString to a beacon name, i.e. "Fernández", through the SDK using the ```[ESTBeaconConnection writeName:completion:]``` method, and am consistently getting the following error:

```Error Domain=com.estimote Code=400 "Unable to connect to Estimote Cloud. Please try again later." UserInfo=0x17667cfc0 {NSLocalizedDescription=Unable to connect to Estimote Cloud. Please try again later.}```

Is this a known issue with utf-8 charsets?

**Comment by jcb1973** [comment]
Thanks for letting us know about this - there was a bug in how we were handling accented characters. We have released a fix for this this morning - please let us know of any further issues.
