### ISSUE TITLE
Exception in SDK on nearable detection

### ISSUE THREAD

**Issue by jacobrosenthal** [Estimote/iOS-SDK#199]
They are SB0 with Nearables OS SA1.0.0, 3.2.5 sdk. Im on ios 8.3, xcode 6.3.2
Ive never seen it in your monitoring example, so it COULD be a result of something Im doing, but I cant find anything different.

I scan with 
[self.nearableManager startMonitoringForType:ESTNearableTypeAll];

and as soon as I bring a device nearby
2015-06-08 16:03:48.880 fact0ryx_ios[343:22802] -[__NSDictionaryI setObject:forKey:]: unrecognized selector sent to instance 0x17027c7c0

I havent figured out how to copy the stack trace so heres a screenshot
![screen shot 2015-06-08 at 4 06 03 pm](https://cloud.githubusercontent.com/assets/455796/8052662/66700b36-0e3e-11e5-90ea-c2f81b4f4ce4.png)

**Comment by jcb1973** [comment]
Hello there - you were doing nothing wrong, we had a bug in our nearables caching. Our apologies! We've released a fix for this this morning. Please let us know if you have any further issues. And thank you for letting us know.
