### ISSUE TITLE
iBeacon not detected

### ISSUE THREAD

**Issue by jefferyleo** [Estimote/iOS-SDK#201]
I've developed an application that using the Estimote iBeacon. Before that, my application will detect the nearby iBeacon with iOS 8.1, but after that, I've format my iPad and upgrade to iOS 8.3, my application is not working anymore, it can't detect any nearby beacon, do you guys know what happen to it? Is it my application problem or the beacon problem?

**Comment by wiktor** [comment]
@jefferyleo Can you download Estimote app from App Store and check if it detects your beacons?

**Comment by jefferyleo** [comment]
@wiktor yea, it has detected the beacon with the offical Estimote app, but previously I could detect the nearby beacons with my own app, but once I've updated to iOS 8.3, my app couldn't detect any beacon now

**Comment by wiktor** [comment]
Can you share the code to detect beacons? What UUID/major/minor you are using?

**Comment by jefferyleo** [comment]
@wiktor Basically, I’m using Swift development to develop my application to iOS.
So in the viewDidLoad() method, I write these code and try to discover whether it got beacons nearby
locationManager.startMonitoringForRegion(beaconRegion)
locationManager.startRangingBeaconsInRegion(beaconRegion)
locationManager(startUpdatingLocation)

After that, I have write these code in the didEnterRegion, which it detects whether the beacons is in range.
let beaconRegion = CLBeaconRegion (proximityUUID: NSUUID(UUIDString: "B9407F30-F5F8-466E-AFF9-25556B57FE6D"), major: CLBeaconMajorValue(), minor: CLBeaconMinorValue(), identifier: "LAB L3 - 04")
manager.startRangingBeaconsInRegion(beaconRegion)
manager.startUpdatingLocation()

**Comment by wiktor** [comment]
Ok, so you are using CoreLocation and not our SDK.
For sanity, can you download Estimote app from App Store and check demos (for ranging & monitoring)?

**Comment by Omarj** [comment]
@wiktor I download the SDK and run example app , it detected all my iBeacon but when I turn on of them to secure UUID the app did not detected it ? "already added appID and token"

**Comment by Saurman** [comment]
This happens from time to time, u have to force close and restar Estimote app for beacons to appear. Maybe same applies to your app

**Comment by heypiotr** [comment]
Looks like it's not an SDK issue if you're using Core Location. If you're still experiencing this, let's discuss on our forums: https://forums.estimote.com

**Comment by jackson140389** [comment]
Hello Guys, I'm using beacon(Moko Beacon) in iOS. Sometimes didExit event didn't call even beacon distance more than 3 km. After I come back to beacon didEnter event didn't call until change the power cycle of the beacon. So please help me out I have already spent more than 5 days to overcome this issue.
