### ISSUE TITLE
Beacon not found after disconnect

### ISSUE THREAD

**Issue by souhl** [Estimote/iOS-SDK#202]
Hi,

we are facing the following issue:

After starting ranging beacons, we find and connect to a beacon in order to get some parameters from it.
This works stable.

But when we disconnect this beacon we don't find it again.

Disconnect is done via 
   [beaconConnection cancelConnection];

After the disconnect was successful - didDisconnectWithError returned no error - we are ranging again, but the beacon is not showing up anymore. Only a restart of the app solves the issue.

Anything else we need to do clean up things, except calling cancelConnection?

Thanks
Sascha

**Comment by martinklimek** [comment]
@souhl can you confirm that device was disconnect looking at bluetooth icon on status bar?

**Comment by souhl** [comment]
@martinklimek oh, yes. it is still connected when I check the settings. So, what do we need to do disconnect properly?

**Comment by martinklimek** [comment]
In iOS here may be delay between sending disconnect request and actual disconnect (bluetooth icon is not highlighted) - can you check if this is actually happening?

**Comment by souhl** [comment]
yes, but nothing happens. at the moment I just call cancelConnection. Do I need to call disconnect, too? When I just call disconnect the app is crashing. When calling cancelConnection on the ESTBeaconConnection do I need to do anything with original CLBeacon object which was used to establish the BeaconConnection?

**Comment by martinklimek** [comment]
actually both disconnect and cancelConnection methods do the same thing. We are going to deprecate cancelConnection method soon. Anyway - do you get didDisconnect callback in 3.2.9?

**Comment by souhl** [comment]
I think I found the issue... will double check later this week.

**Comment by martinklimek** [comment]
Cool, let me know!

**Comment by martinklimek** [comment]
Actually I was looking more into your issue and did disconnect event was missing. Test with 3.2.10.

**Comment by martinklimek** [comment]
@souhl any news on that?

**Comment by souhl** [comment]
@martinklimek we had a software bug which simply reconnected to lost connections all the time... closing this.
