### ISSUE TITLE
notifyEntryStateOnDisplay not working since...?

### ISSUE THREAD

**Issue by benjaminhallock** [Estimote/iOS-SDK#203]
notifyEntryOnDisplay is a boolean property on the beaconRegion.

It's supposed to call didDetermineState when the display is turned on (inside a region)...

I use that to trigger a notification.

That stopped working a long time ago (v.2.1.5) and I complained back then.

I'm using a virtual beacon on another iPad via EstimoteSDK, which works great, I just can't get this method to call didDetermineState when the display is turned on.

Note: v.2.1.5 still had this problem when I just tested. So this must be iOS related.

**Comment by heypiotr** [comment]
SDK 3.x no longer uses ESTBeaconRegion, but the native CLBeaconRegion instead. So I suspect this bug should be gone in SDK 3.x. Feel free to reopen otherwise.

**Comment by benjaminhallock** [comment]
I'll check... I think  disabled it tho.
