### ISSUE TITLE
[CLLocationManager requestAlwaysAuthorization]: unrecognized selector sent to instance

### ISSUE THREAD

**Issue by BogdanSr** [Estimote/iOS-SDK#204]
When I start monitoring beacons on iOS 7 my app crashes when I call "startMonitoringForIdentifier:" method. This method calls "requestAlwaysAuthorization" with was introduced in iOS 8 without "respondsToSelector:" check.

Documentation says that SDK supports iOS 7, is there some kind of bug in the SDK or Documentation needs to be updated?

**Comment by heypiotr** [comment]
Yup, that's a bug, thanks for pointing this out—we'll work on a fix.

**Comment by heypiotr** [comment]
Hmm, this has been fixed a long time ago, closing (:
