### ISSUE TITLE
Nearables not detected with CoreLocation

### ISSUE THREAD

**Issue by bryan1anderson** [Estimote/iOS-SDK#205]
I have had no problem detecting Estimote Beacons using core location. However nearables are not detectable. That to me means they are not broadcasting over iBeacon frequency.

How do I fix this? Is this issue common, or expected?

Also the estimote beacons app does not detect nearables.

**Comment by heypiotr** [comment]
Stickers broadcast the iBeacon packet approximately once every 10 seconds when still, and once every 5 seconds when in motion. They should still be detectable, only less often. Keep in mind stickers don't broadcast under the default Estimote UUID—each sticker has their own UUID+major+minor combination, which you can read in the Estimote app.

This default advertising frequency is there to reduce the energy usage—stickers have a battery that's an order of magnitude smaller than that of the bigger beacons, so some trade-offs are necessary not to have them run out of juice too quickly. That's the price for the much smaller size.

We're planning to make the advertising settings configurable via a firmware upgrade that'll be coming later this year.

About the app not detecting your stickers: would you mind if we move this conversation to [forums.estimote.com](https://forums.estimote.com), or to [contact@estimote.com](mailto:contact@estimote.com)? We'd prefer to keep GitHub issues about the SDK. Just post on forums or shoot us an email and we'll assist shortly.
