### ISSUE TITLE
Warnings in Non-ARC Project

### ISSUE THREAD

**Issue by sjacs5537** [Estimote/iOS-SDK#207]
Hi,

There are a number of semantic warnings that should be fixed for missing property attributes:

In ESTBeaconVO.h:
@property (nonatomic) NSString *city;
@property (nonatomic) NSString *country;
@property (nonatomic) NSString *formattedAddress;
@property (nonatomic) NSString *stateName;
@property (nonatomic) NSString *stateCode;
@property (nonatomic) NSString *streetName;
@property (nonatomic) NSString *streetNumber;
@property (nonatomic) NSString *zipCode;

Warning:
EstimoteSDK.framework/Headers/ESTBeaconVO.h:38:1: No 'assign', 'retain', or 'copy' attribute is specified - 'assign' is assumed

Thanks

**Comment by heypiotr** [comment]
Thanks for your report. Estimote SDK relies on ARC for memory management, and to use it in a non-ARC project will probably mean trouble. I don't think Xcode even allows creating non-ARC projects anymore, and it'd be a huge investment on our side to make the SDK non-ARC compatible, so we won't be doing that. What's the reason you're on a non-ARC project? Legacy code?
