### ISSUE TITLE
Compile Framework with Bitcode

### ISSUE THREAD

**Issue by justin-taylor** [Estimote/iOS-SDK#208]
The latest Xcode complains about EstimoteSDK.framework/EstimoteSDK(ESTBulkUpdater.o) not containing bitcode. Xcode suggests to rebuild the framework with bitcode enabled.

For now it is simple enough to disable bitcode in the project build settings.

**Comment by heypiotr** [comment]
The upcoming release of the SDK (should hit GitHub mid next week) will come with bitcode enabled.

**Comment by StephenWilson** [comment]
It still doesn't work...

error: bitcode_strip .../my_project/EstimoteSDK.framework/Versions/A/EstimoteSDK: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/bitcode_strip exited with 1

**Comment by heypiotr** [comment]
I tried it with a few of my projects and I'm not getting any errors. Can you try with a fresh Xcode 7 project? Can you try cleaning the build folder of the project that gives you errors? Remember to change the "Enable bitcode" option back to "YES."

**Comment by StephenWilson** [comment]
OK, that worked fine. Looks like there's something else going on. Thanks anyway.

**Comment by heypiotr** [comment]
All right—once you figure out what was wrong, feel free to post it here for other to know (:

**Comment by StephenWilson** [comment]
My problem had nothing to do with the estimote sdk or bitcode. Xcode kindly ruined my project, I cloned again and made the exact same changes again which fixed it instantly. Yet another victory for the prankster genius that is Xcode.
