### ISSUE TITLE
Cannot compile using V3.7 framework

### ISSUE THREAD

**Issue by sjacs5537** [Estimote/iOS-SDK#209]
Hi,

I got a lot of error when I try to upgrade the framework from 3.6 to 3.7.

![untitled](https://cloud.githubusercontent.com/assets/5335290/10366568/ebd1f64e-6dfd-11e5-8798-3701db723107.png)

**Comment by lpikor** [comment]
Which version of Xcode you are using?

**Comment by sjacs5537** [comment]
6.4.0

**Comment by lpikor** [comment]
Can you download Xcode 7.0 and try to recompile? It looks like it's connected to Objective-C generics introduced in latest version of iOS SDK.

**Comment by sjacs5537** [comment]
It can be compiled in Xcode7.
Will the SDK start from V3.7 support Xcode7+ only?

**Comment by heypiotr** [comment]
Correct. There's rarely a reason not to update to the latest version of Xcode and iOS SDK, Apple stops supporting the older ones as soon as their's a new one available. If you need to temporarily stick to Xcode 6, you can download Estimote SDK 3.6.0 here: https://github.com/Estimote/iOS-SDK/releases/tag/3.6.0
