### ISSUE TITLE
Bitcode support?

### ISSUE THREAD

**Issue by kaminoo** [Estimote/iOS-SDK#210]
Hi.
It says on the release notes for 3.7.0 that Bitcode support is enabled, however when compiling with the new library it still says bitcode is not supported.
Best to all

**Comment by heypiotr** [comment]
Works for me. Make sure you're really on 3.7.0, and try doing a full rebuild.

<img width="776" alt="screen shot 2015-10-26 at 17 26 10" src="https://cloud.githubusercontent.com/assets/1155764/10735165/f95c1198-7c06-11e5-85b6-125bd89944d3.png">

```
Piotr at Piotrs-MacBook in ~/Code/xcode/Playground
$ cat Podfile.lock 
PODS:
  - EstimoteSDK (3.7.0)

DEPENDENCIES:
  - EstimoteSDK

SPEC CHECKSUMS:
  EstimoteSDK: 3ecb389bf661493612a5a70ce1cd8d3c45b4561b

COCOAPODS: 0.39.0
```
