### ISSUE TITLE
Eddystone manager

### ISSUE THREAD

**Issue by kaminoo** [Estimote/iOS-SDK#211]
Hi.
We are seeing a problem when using the Eddystone manager.
We do realize background detection is tricky, but it should at least detect beacons once (no duplicates allowed). We are testing this consistently using the Eddystone Google SDK.

However when using your SDK new beacons are not detected in the background.

Your SDK is not open source, so we can't take a look at what is being done behind scenes with CoreBluetooth.

But can you guys test it and let us know? And compare to the Google SDK and see if the same applies?

Best.
Sebastian

**Comment by martinklimek** [comment]
Hi @kaminoo, 

Background discovery is not supported yet by Estimote SDK. Only foreground discovery is possible now. We have background eddystone support on our roadmap but I can not give you any ETA yet. I will close this issue as it is feature request.
