### ISSUE TITLE
How to have range multiple Beacons?

### ISSUE THREAD

**Issue by kohdesmond** [Estimote/iOS-SDK#215]
Hi I'm new with Estimote.

i followed the tutorial 3 and successfully received a reply from just one beacon.
[CLBeacon (uuid:<__NSConcreteUUID 0x127efb5c0> 857E743F-FDEC-81B3-F2C6-5254D2BC9AE3, major:30003, minor:15003, proximity:3 +/- 3.37m, rssi:-64)]

what should i do to get a list of beacons back? all the beacons have a major starting 30000 and a minor starting 15000

let beaconManager = ESTBeaconManager()

let desmondBeaconRegion = CLBeaconRegion(proximityUUID: NSUUID(UUIDString: "CCAA0107-98FB-4FBA-4803-92CBAE08A909")!,identifier: "Desmond region")

self.beaconManager.startRangingBeaconsInRegion(self.NikitaBeaconRegion)

**Comment by heypiotr** [comment]
Please repost your question on our forums, we'll be happy to help!
https://forums.estimote.com

We want to keep GitHub issues for bug reports only.
