### ISSUE TITLE
How do I use Telemetry Code

### ISSUE THREAD

**Issue by krishnatgkk** [Estimote/iOS-SDK#220]
Team

I am new to Objective-C development and wanted to get started with Beacons and check on Beacon temperature and GPIO sensors.  can anybody help me with that. I have used the temperature code in ProximityContent project under viewController.m file.
I have Location beacons with telemetry enabled.  please let me know if I am not doing the right thing.

Thanks
Krishna

**Comment by nisit15** [comment]
I'm waiting for this answer.

**Comment by heypiotr** [comment]
Check out our Telemetry tutorial on Developer Portal:
http://developer.estimote.com/sensors/estimote-telemetry/

If you have any further questions how to scan for Telemetry, post on our forums: (We want to keep GitHub issues for bugs only.)
https://forums.estimote.com/
