### ISSUE TITLE
Archiving: Linker command failed with EstimoteSDK 4.4.0

### ISSUE THREAD

**Issue by soequelle** [Estimote/iOS-SDK#221]
Hello, I try to Archive the build to publish in app store and I have the same issue with EstimoteSDK 4.4.0 describe in this https://goo.gl/tzGy4O 
but I can't solve the problem

Using Xcode Version 7.3 (7D175)
ld: library not found for -lPods-EstimoteSDK
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Help me please, I need upload the app to app store soon

Thank you.

**Comment by boomi1990** [comment]
Hi,

I am also facing the same issue. Is that issue solved soequelle?

Thanks
Boominadha Prakash M

**Comment by soequelle** [comment]
Hello @boomi1990,
Yes, I could solve the issue. If you use Pod for library management, just delete the libEstimoteSDK.a from section "Linked Frameworks and Libraries"
