### ISSUE TITLE
iOS 10 ESTBeaconConnection - CLBeacon Error

### ISSUE THREAD

**Issue by gnazarkin** [Estimote/iOS-SDK#233]
When connecting to a beacon on iOS 10 I'm getting an error. 
`ESTBeaconConnection *connection = [ESTBeaconConnection connectionWithProximityUUID:uuid major:major minor:minor delegate:self];` results in

 [<CLBeacon 0x174013020> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key proximityUUID.

Framework problem?

**Comment by jingdao** [comment]
I am also having the same problem.

ESTBeaconConnection *connection = [[ESTBeaconConnection alloc] initWithBeacon:beacon delegate:self startImmediately:YES];

[<CLBeacon 0x17001f680> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key proximityUUID.

**Comment by ferologics** [comment]
@gnazarkin were you able to resolve this issue in the meantime?

**Comment by gnazarkin** [comment]
@ferologics I looked through the forum and couldn't find anything when I first encountered this issue. Still haven't resolved it. Only happens on iOS 10 for me

**Comment by ferologics** [comment]
@gnazarkin alright, looks like we're already working on this issue, expect a fix in the nearest SDK release 🔜  🙂

**Comment by hardikpatelit123** [comment]
i am also having the same issues with the estimote beacon connection in IOS 10.
so please if anyone got update regarding this then update on this.

**Comment by gnazarkin** [comment]
@ferologics any updates on this?

**Comment by hardikpatelit123** [comment]
no we not gettting any updates regarding this from the Estimote team also.
i try to communicate with the Estimote Team more time but not getting any response from Estimote Team.

**Comment by hardikpatelit123** [comment]
we try with the latest version of Estimote SDK and it's works properly in the IOS 10 and all above versions.

**Comment by ferologics** [comment]
Sorry if we weren't responsive to your requests. We get many many support emails every day and it's tough to balance 🔢 . . .  Glad to hear that your issue was resolved! closing

**Comment by gnazarkin** [comment]
Not getting the CLBeacon Error anymore but now getting [CoreBluetooth] XPC connection invalid when connecting to beacon

**Comment by ferologics** [comment]
@gnazarkin could you please open a new issue for this? thanks!

**Comment by gnazarkin** [comment]
@ferologics #239
