### ISSUE TITLE
Bluetooth message

### ISSUE THREAD

**Issue by yamifr07** [Estimote/iOS-SDK#238]
Hi, I would like to change the default message "Turning on bluetooth will improve location accuracy", displayed when bluetooth is off. Any idea?

**Comment by ferologics** [comment]
2nd link - [here you go](http://www.letmegooglethat.com/?q=change+bluetooth+message+ios)

**Comment by ferologics** [comment]
we also have it on our [support forums](https://forums.estimote.com/t/ios-bluetooth-custom-message/2941)
