### ISSUE TITLE
[Question] How to get a list of currently monitored regions

### ISSUE THREAD

**Issue by okonon** [Estimote/iOS-SDK#258]
@martinklimek hello, i was wondering how can i get a list of currently monitored regions?
Thanks

**Comment by jackson13info** [comment]
@okonon Checkout the [ESTBeaconManager](https://github.com/Estimote/iOS-SDK/blob/master/EstimoteSDK/EstimoteSDK.framework/Headers/ESTBeaconManager.h#L223). In that class there is a `monitoredRegions` attribute which should let you do exactly what you are trying to do.

**Comment by okonon** [comment]
Thanks!
