### ISSUE TITLE
ESTMonitoringV2Manager not detecting beacons

### ISSUE THREAD

**Issue by ademars94** [Estimote/iOS-SDK#262]
I installed version 4.20 today via CocoaPods (had to use git, was not available in pod repo):
`pod 'EstimoteSDK', :git => 'https://github.com/Estimote/iOS-SDK.git', :commit => '51c0bf3'`

- I have set up my `Info.plist` for all location and bluetooth monitoring.

- My `AppDelegate` implements the `ESTMonitoringV2ManagerDelegate` protocol.

- My `didEnter...`, `didExit...`, and `didFail` delegate methods are in place, and they are not being triggered, which must mean I am not detecting the beacon.

- The following is in my `didFinishLaunching`:
```swift
ESTConfig.setupAppID("my-app-id", andAppToken: "my-app-token")
let monitoringManager = ESTMonitoringV2Manager(desiredMeanTriggerDistance: 1.0, delegate: self)
monitoringManager.startMonitoring(forIdentifiers: ["my-beacon-identifier"])
```

The documentation on the `ESTMonitoringManager` and the `ESTMonitoringV2Manager` seem to be pretty light.  Am I missing something that I need to get this working?

**Comment by stephandue** [comment]
Facing the exact same problem.

**Comment by airalex** [comment]
Hey, @ademars94, @stephandue, there's a couple of things you can check:
- Are your beacons configured for Estimote Monitoring? https://community.estimote.com/hc/en-us/articles/226144728-How-to-enable-Estimote-Monitoring-
- @ademars94, your code snippet contains `"my-app-id"`, `"my-app-token"`, `"my-beacon-identifier"`. Make sure you replaced these strings with values related to your Estimote Cloud account (https://cloud.estimote.com/#/apps for App ID & App Token, https://cloud.estimote.com/#/ for beacon identifiers)
- Just to get it out of the way - please make sure you have Bluetooth on


Have you tried using Estimote Cloud app templates? They should work out of the box - you only need to configure the provisioning profile: https://cloud.estimote.com/#/apps/add/notification

**Comment by ademars94** [comment]
@airalex I replaced the strings in my code snippet with generic values as to not expose them on GitHub.  Our application is using the keys from Estimote Cloud.  The beacons are configured to use Estimote Monitoring, as they are working with v1 Monitoring.  Bluetooth is definitely on.

I am hoping you might be able to point me in the direction of some proper documentation for the v2 Monitoring API.  I have seen the class reference, but that is just method signatures and doesn't really show how to implement v2 Monitoring.
