### ISSUE TITLE
Notification example

### ISSUE THREAD

**Issue by anumshk27** [Estimote/iOS-SDK#282]
How to fetch cloud attachments when  `didEnterDesiredRangeOfBeaconWithIdentifier` get called ?

**Comment by chwastek** [comment]
Hey @anumshk27 
you cannot unfortunately. At least not with our (good but old) Estimote iOS SDK. The whole tags, attachments and proximity experience is within [Proximity SDK](https://github.com/Estimote/iOS-Proximity-SDK), which has reached lately its [mature 1.0.0 🎉](https://github.com/Estimote/iOS-Proximity-SDK/releases/tag/v1.0.0). You can read more as well [here](
https://blog.estimote.com/post/176019935745/updated-proximity-sdk-introduces-tag-monitoring) what we introduced and why.
